### ISSUE TITLE
Criar Projeto na IDE

### ISSUE THREAD

**Issue by brunoqp78** [brunoqp78/AtividadeA8-GrupoX#4]
Criar projeto na IDE XXXX e vinculá-lo ao repositório do GitHub. (Vocês irão definir qual IDE). Quando der o commit, finalize o comentário com close #1, assim marca a atividade como concluída. Essa Issues deve ser criada pelo Lider.

**Comment by brunoqp78** [comment]
O código da Issues não é #1, o código correto é #4

**Comment by brunoqp78-2** [comment]
Me adicione no projeto
